"use client";

import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { GitCommit, Filter, ArrowLeft, RefreshCw } from 'lucide-react';
import Link from 'next/link';

// Data imports (generated by script)
import commitData from '@/data/commits.json';
import authorData from '@/data/authors.json';
import branchData from '@/data/branches.json';

// Components
import CommitFilters from '@/components/CommitFilters';
import CommitList from '@/components/CommitList';

export default function CommitHistoryPage() {
  const [filters, setFilters] = useState({
    branch: 'all',
    author: 'all',
    startDate: '',
    endDate: '',
  });

  const [filteredCommits, setFilteredCommits] = useState(commitData);
  const [isRefreshing, setIsRefreshing] = useState(false);

  useEffect(() => {
    let results = [...commitData];

    if (filters.branch !== 'all') {
      results = results.filter(c => c.branch === filters.branch);
    }

    if (filters.author !== 'all') {
      results = results.filter(c => c.author === filters.author);
    }

    if (filters.startDate) {
      const start = new Date(filters.startDate);
      results = results.filter(c => new Date(c.date) >= start);
    }

    if (filters.endDate) {
      const end = new Date(filters.endDate);
      // Set end of day for the end date
      end.setHours(23, 59, 59, 999);
      results = results.filter(c => new Date(c.date) <= end);
    }

    setFilteredCommits(results);
  }, [filters]);

  const handleRefresh = () => {
    setIsRefreshing(true);
    // In a real app, this might fetch from an API
    // Here we just simulate a reload of the static JSON
    setTimeout(() => {
      setIsRefreshing(false);
    }, 1000);
  };

  return (
    <main className="min-h-screen bg-[#0a0f1a] text-slate-200 font-sans selection:bg-blue-500/30">
      {/* Background Decor */}
      <div className="fixed inset-0 overflow-hidden pointer-events-none">
        <div className="absolute top-[-10%] left-[-10%] w-[40%] h-[40%] bg-blue-600/10 blur-[120px] rounded-full" />
        <div className="absolute bottom-[-10%] right-[-10%] w-[40%] h-[40%] bg-emerald-600/10 blur-[120px] rounded-full" />
      </div>

      <div className="max-w-6xl mx-auto px-6 py-12 relative z-10">
        {/* Header */}
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-6 mb-12">
          <div className="space-y-2">
            <Link 
              href="/"
              className="inline-flex items-center gap-2 text-slate-400 hover:text-white transition-colors mb-4 group"
            >
              <ArrowLeft size={16} className="group-hover:-translate-x-1 transition-transform" />
              <span className="text-xs font-bold uppercase tracking-widest">Back to Dashboard</span>
            </Link>
            <h1 className="text-5xl font-black uppercase tracking-tighter text-white flex items-center gap-4">
              Commit <span className="text-blue-500">History</span>
              <GitCommit size={40} className="text-blue-500/50" />
            </h1>
            <p className="text-slate-400 font-medium max-w-xl">
              Track the evolution of HCTPL ecosystem projects. Browse changes, contributors, and deployment markers across all branches.
            </p>
          </div>

          <div className="flex items-center gap-3">
            <button 
              onClick={handleRefresh}
              className={`p-4 bg-white/5 border border-white/10 rounded-2xl text-slate-300 hover:text-white hover:bg-white/10 transition-all ${isRefreshing ? 'animate-spin' : ''}`}
              title="Refresh History"
            >
              <RefreshCw size={20} />
            </button>
            <div className="px-6 py-4 bg-blue-600 rounded-2xl shadow-xl shadow-blue-500/20 text-white font-black uppercase tracking-widest text-xs">
              {filteredCommits.length} Commits
            </div>
          </div>
        </div>

        {/* Filters Section */}
        <section className="mb-12">
          <div className="flex items-center gap-2 mb-4 text-slate-400">
            <Filter size={14} />
            <span className="text-[10px] font-black uppercase tracking-[0.2em]">Filter Repository</span>
          </div>
          <CommitFilters 
            branches={branchData}
            authors={authorData}
            filters={filters}
            onFilterChange={setFilters}
          />
        </section>

        {/* Results Section */}
        <section className="min-h-[400px]">
          <AnimatePresence mode="wait">
            <motion.div
              key={filteredCommits.length + JSON.stringify(filters)}
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              transition={{ duration: 0.3 }}
            >
              <CommitList commits={filteredCommits} />
            </motion.div>
          </AnimatePresence>
        </section>

        {/* Footer info */}
        <div className="mt-20 pt-8 border-t border-white/5 flex flex-col md:flex-row justify-between items-center gap-4 text-slate-500 text-[10px] font-black uppercase tracking-widest">
          <div>HCTPL ECOSYSTEM • COMMIT TRACKER V1.0</div>
          <div className="flex items-center gap-4">
            <span className="flex items-center gap-1"><div className="w-2 h-2 rounded-full bg-emerald-500" /> LIVE REPO</span>
            <span className="flex items-center gap-1"><div className="w-2 h-2 rounded-full bg-blue-500" /> STABLE BUILD</span>
          </div>
        </div>
      </div>
    </main>
  );
}
